class StudentCohort:
    def __init__(self, cohort_id: str):
        self.cohort_id = cohort_id

    def add_student(self, student, student_policy): ...

    def get_student(self, student_id): ...

    def get_students(self): ...

    def notify(self, message): ...
